### ISSUE TITLE
[Issue] Readme Text Indecipherable on Dark Mode

### ISSUE THREAD

**Issue by GoodPro712** [MCDReforged/PluginCatalogue#114]
### Description
The dark blue text in the readme file is barely readable on Github dark mode
![image](https://user-images.githubusercontent.com/45357714/121804400-978b3280-cc89-11eb-9e78-b74be8d02b5e.png)

**Comment by zhang-anzhi** [comment]
What do you want?

**Comment by zhang-anzhi** [comment]
Use your head or use your imagination
