### ISSUE TITLE
update timed_quick_backup_multi

### ISSUE THREAD

**Issue by NanamiNakano** [MCDReforged/PluginCatalogue#238]
[TISUnion/TimedQBM](https://github.com/TISUnion/TimedQBM/) code has been updated to 1.2.0 but not released.
I packaged this plugin here [https://github.com/NanamiNakano/TimedQBM/releases/tag/v1.2.0](https://github.com/NanamiNakano/TimedQBM/releases/tag/v1.2.0)
Please update plugin info and create a release in the main repo.

**Comment by NanamiNakano** [comment]
Feedback to plugin developers as well
[https://github.com/TISUnion/TimedQBM/issues/6](https://github.com/TISUnion/TimedQBM/issues/6)

**Comment by alex3236** [comment]
Nothing to do with this repo
