### ISSUE TITLE
插件仓库下载列表未准确识别

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#239]
插件 StartStopHelperR 的下载列表未识别到 release
https://github.com/MCDReforged/PluginCatalogue/blob/catalogue/plugins/start_stop_helper_r/readme.md
https://github.com/AnzhiZhang/MCDReforgedPlugins/releases/tag/start_stop_helper_r-v0.1.0

原因未知
https://github.com/MCDReforged/PluginCatalogue/commit/9e71dc7de40093c6208ee1645b311cf614968521#diff-a2f8344b51630c0fbfc8bb902f079e56afa0076cdae77db97be7b7c6970fce0c

**Comment by ra1ny-yuki** [comment]
这是生成该说明文档commit的action（Scheduled update #14168），于Fetch data阶段获取start_stop_helper_r release后可见报错：not 200 status code when fetching repository file readme-zh_cn.md: 404

https://github.com/MCDReforged/PluginCatalogue/actions/runs/3922973249/jobs/6706276907

**Comment by AnzhiZhang** [comment]
> 这是生成该说明文档commit的action（Scheduled update #14168），于Fetch data阶段获取start_stop_helper_r release后可见报错：not 200 status code when fetching repository file readme-zh_cn.md: 404
> 
> https://github.com/MCDReforged/PluginCatalogue/actions/runs/3922973249/jobs/6706276907

这个问题看起来不是这个插件的，与 `region_file_updater` `tpm` `wiki_request` `smart_servertime` `run_some_commands` 这几个相关的

```text
Fetched release info of region_file_updater
  File "/home/runner/work/PluginCatalogue/PluginCatalogue/scripts/plugin.py", line 228, in load_from_json
Fetched release info of tpm
    introduction_translations[lang] = self.get_repos_text(file_location)
Fetched release info of wiki_request
  File "/home/runner/work/PluginCatalogue/PluginCatalogue/scripts/plugin.py", line 281, in get_repos_text
Fetched release info of smart_servertime
    raise Exception('not 200 status code when fetching repository file {}: {}'.format(file_path, resp.status_code))
Fetched release info of run_some_commands
Exception: not 200 status code when fetching repository file readme-zh_cn.md: 404
```

**Comment by AnzhiZhang** [comment]
找到原因了，请求 API 并没有做翻页，导致没有获取到较老的 release

plugin.py
```python
url = f'https://api.github.com/repos/{plugin.repos_path}/releases'
resp: Optional[List[dict]]
new_etag: str
resp, new_etag = utils.request_github_api(url, etag=self.etag)
```

utils.py
```
response = requests.get(url, proxies=constants.PROXIES, headers=headers)
```

**Comment by AnzhiZhang** [comment]
根据文档，只返回了30个release……
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases

**Comment by alex3236** [comment]
> 根据文档，只返回了30个release…… https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases

似乎没有给总页数？

**Comment by AnzhiZhang** [comment]
可以翻到为空的最后一页就行了，或者查看有内容的最后一页是不是达到最大数量

**Comment by alex3236** [comment]
https://github.com/MCDReforged/PluginCatalogue/compare/master...multi-page-releases-support
简单地修了一下
但对于类似 @AnzhiZhang 那种单 repo 多插件，每个插件检查时都会重新获取 Releases 的每一页，有点浪费 API 使用次数

**Comment by AnzhiZhang** [comment]
> 但对于类似 @AnzhiZhang 那种单 repo 多插件，每个插件检查时都会重新获取 Releases 的每一页，有点浪费 API 使用次数
无论多repo还是单repo，总共需要获取的release总数是不变的，反而单repo会节省使用次数，因为不到一页的插件被合并了
前提是做好release获取的缓存，不要到一个插件读一次所有release

**Comment by alex3236** [comment]
> > 但对于类似 @AnzhiZhang 那种单 repo 多插件，每个插件检查时都会重新获取 Releases 的每一页，有点浪费 API 使用次数
> 
> 无论多repo还是单repo，总共需要获取的release总数是不变的，反而单repo会节省使用次数，因为不到一页的插件被合并了 前提是做好release获取的缓存，不要到一个插件读一次所有release

对的 理论上做好缓存可以节省API使用次数 但反正我这个分支暂时没做（
