### ISSUE TITLE
在 meta 中储存 `plugin_info.json` 中的 `related_path` 和 `branch` 信息

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#256]
在 meta 中没有相对路径信息，用户打开仓库后还需要再找路径才能看到插件和文档
如果直接在文档超链接直接点击打开到相对路径，可能会更加方便
![image](https://user-images.githubusercontent.com/37402126/221417882-9f85d71c-54cd-44d3-b80a-d22e58c3bac7.png)
文档同理
![image](https://user-images.githubusercontent.com/37402126/221417889-3a748e55-a57b-476e-9e16-f9a669a165fb.png)

**Comment by Fallen-Breath** [comment]
请用正确的中文语法准确的描述你所要的需求，而非省略过多主谓宾上下文，导致该 issue 难以理解

**Comment by AnzhiZhang** [comment]
将 `plugin_info.json` 中的 `related_path`  保留在生成的meta中，以便于访问正确的插件文件夹。

**Comment by AnzhiZhang** [comment]
今天发现没有 `related_path` 无法找到 `introduction` 提供的文件
