### ISSUE TITLE
[讨论]：检查插件分支是否存在

### ISSUE THREAD

**Issue by alex3236** [MCDReforged/PluginCatalogue#260]
例如 [`ToDoList`](https://github.com/MCDReforged/PluginCatalogue/blob/master/plugins/todolist/plugin_info.json)，分支与实际不匹配。

github api似乎在分支不存在的时候会跳转默认分支，因此可以正常抓取，但这样是不是合理？

**Comment by zyxkad** [comment]
> github api似乎在分支不存在的时候会跳转默认分支，因此可以正常抓取

Github api在分支不存在时似乎不会自动跳转到默认分支? 例如 <https://api.github.com/repos/Flash-Z/MCDReforgedPlugins/ToDoList/readme?ref=master>

**Comment by Fallen-Breath** [comment]
请给出具体的“github api似乎在分支不存在的时候会跳转默认分支，因此可以正常抓取”的例子

插件仓库 meta 分支的数据拉取中，对于仓库内的文件，是从 `https://raw.githubusercontent.com` 拉取的文件内容，并未使用 github api

对于 ToDoList 这个插件，其仓库中分支为 main，但其 `plugin_info.json` 中填写的是 master。对此：

- https://raw.githubusercontent.com/Flash-Z/MCDReforgedPlugins/main/ToDoList/mcdreforged.plugin.json ：正常访问
- https://raw.githubusercontent.com/Flash-Z/MCDReforgedPlugins/master/ToDoList/mcdreforged.plugin.json ：正常访问
- https://raw.githubusercontent.com/Flash-Z/MCDReforgedPlugins/foobar/ToDoList/mcdreforged.plugin.json ：无法访问

猜测可能是 github 自动将 master 重定向至 main，但也仅会做这一个重定向。对于其他不存在的分支，依然无法访问

**Comment by alex3236** [comment]
因此是有必要检查的

**Comment by Fallen-Breath** [comment]
> 因此是有必要检查的

请给出理由，以及“请给出具体的“github api似乎在分支不存在的时候会跳转默认分支，因此可以正常抓取”（https://github.com/MCDReforged/PluginCatalogue/issues/260#issuecomment-1479032138）的例子”。根据目前情况而言，我认为是无需做检查

**Comment by alex3236** [comment]
不好意思。也许如你所说，“github 自动将 master 重定向至 main，但也仅会做这一个重定向。对于其他不存在的分支，依然无法访问”。因此，在处理 PR 时应当对此进行检查。抓取 meta 时似乎不必再做检查，因为无法访问已经可以说明问题。
