### ISSUE TITLE
`labels` is not available in `MetaInfo`

### ISSUE THREAD

**Issue by Ivan-1F** [MCDReforged/PluginCatalogue#262]
Currently there's no way to get plugin labels from https://raw.githubusercontent.com/MCDReforged/PluginCatalogue/meta/plugins.json

This breaks plugin managers based on this json file

**Comment by Fallen-Breath** [comment]
> `labels` is not available in `MetaInfo`
> Currently there's no way to get plugin labels from

This is an intended change to split the meta info and publishment info of a plugin

But yeah, an aggregation of `plugin_info.json` might be useful
