### ISSUE TITLE
貌似如果开了tw的发言时间显示就会同时出现两条一样的对话

### ISSUE THREAD

**Issue by DIOJOIO** [MCDReforged/PluginCatalogue#265]
![image](https://user-images.githubusercontent.com/87429221/236600517-98b34e1d-6442-42f8-ba94-13797e95078e.png)

**Comment by alex3236** [comment]
没猜错的话你用的是ColoredChat，麻烦去对应的插件仓库提Issue。
没记错的话这个问题是插件原理导致的，建议改用Mod或插件

**Comment by AnzhiZhang** [comment]
该插件的原理就是这样的，与本仓库无关
