### ISSUE TITLE
PR 未创建有效文件时，Actions 检查结果为通过

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#308]
#307 未上传有效的插件文件，但两个检查结果均为通过。是否可能更新 actions 以检查是否是是新增插件的 PR 且文件有效？
https://github.com/MCDReforged/PluginCatalogue/actions/runs/7328987096/job/19958141432
https://github.com/MCDReforged/PluginCatalogue/actions/runs/7328987097/job/19958141587

**Comment by alex3236** [comment]
大可不必（

**Comment by alex3236** [comment]
如果我只是修改一下introduction，怎么说呢？不怎么好判断吧

**Comment by AnzhiZhang** [comment]
主要难点是区分是否是涉及插件库的变动还是仓库本身，修改introduction自然可以通过
