### ISSUE TITLE
[问题] 插件Meta中作者信息与Catalogue不一致的处理方式

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#311]
例如 [AdvancedWhitelistR](https://github.com/EMUnion/AdvancedWhitelistR)，其插件 [mcdreforged.plugin.json](https://github.com/EMUnion/AdvancedWhitelistR/blob/master/mcdreforged.plugin.json) 列出的作者 `GamerNoTItle` 并未提交到插件仓库 [plugin info](https://github.com/MCDReforged/PluginCatalogue/blob/master/plugins/advanced_whitelist_r/plugin_info.json) 的作者列表，这会导致生成的目录和元数据无法包含该作者。

请问该类情况的预期是如何处理的？

**Comment by alex3236** [comment]
上述例子中，meta信息为：
```
    "author": ["noionion", "GamerNoTItle"]
```
仓库信息为：
```
"name": "GamerNoTitle",
```
其中 Title 大小写不一致。

**Comment by alex3236** [comment]
另外，此问题也存在于：
- 插件作者发生增删或变动，但未修改插件仓库信息，导致作者信息不一致。

**Comment by alex3236** [comment]
个人认为，插件作者这类可能在提交到 Catalogue 后变动，且已存在于 Meta 中的信息，应考虑从 Catalogue 中删去

**Comment by Fallen-Breath** [comment]
预期表现即为本 issue 所述表现

**Comment by alex3236** [comment]
> 预期表现即为本 issue 所述表现

想问一下
- 是否有必要在 Action 的 Summary 中体现作者不一致？
- 出于什么考虑同时在 Catalogue 和 Meta 中存在作者信息？

**Comment by AnzhiZhang** [comment]
> * 是否有必要在 Action 的 Summary 中体现作者不一致？
> * 出于什么考虑同时在 Catalogue 和 Meta 中存在作者信息？

不是作者不一致，是作者缺失

仓库中为声明的作者，插件 meta 一般是做新版的作者，不同的版本可能也有不同的作者
