### ISSUE TITLE
下载量统计不准确

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#314]
更新的插件下载量统计方式只计算一个附件，若插件发布多个变体（如 `pyz` 和 `mcdr`），只会统计部分的有效下载量。

相关代码：https://github.com/MCDReforged/PluginCatalogue/blob/a5ade665a9426ef2aeaa6f57f1a66ac352fdee5e/scripts/meta/release.py#L186-L190

**Comment by alex3236** [comment]
这个其实问题不大吧（
