### ISSUE TITLE
handle external markdown files links with relative path

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#322]
Currently, external markdown files' links are written by scripts, but relative path used in links are not handled. However, github can handle these links with relative path, but it would be better to add handling for it to improve simplicity and stability.

Example:

https://github.com/MCDReforged/PluginCatalogue/blob/ca4f659db42d9222e500a4e449c14d37380ad6c5/plugins/bot/readme.md?plain=1#L256

See Also:

https://github.com/MCDReforged/PluginCatalogue/commit/c426edcbc1add6015edb626dc939b7f3e3a80572

**Comment by Fallen-Breath** [comment]
What is your expected behavior for this feature request? It seems to work as intended since the example markdown link you showed is untouched

**Comment by AnzhiZhang** [comment]
As mentioned above, simplify links with relative path, e.g.

```
https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/src/bot/../fastapi_mcdr
```

will be simplified to

```
https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/src/fastapi_mcdr
```

**Comment by Fallen-Breath** [comment]
It is really necesary at all? Urls with related paths aready work correctly without any issue. Unnecessary simplification will add more complexity onto the rewriter code

**Comment by AnzhiZhang** [comment]
Not necesary, GitHub will handle links like that. It's totally depends on you
