### ISSUE TITLE
PlayTime插件未遵循开源规范，申请暂时移除对该插件的收录

### ISSUE THREAD

**Issue by Aimerny** [MCDReforged/PluginCatalogue#340]
pt插件作者未经本人同意擅自修改并分发playerLastPlay插件仓库，未遵循开源规范。期间沟通未果，申请移除pt插件的收录

Plp仓库: https://github.com/Aimerny/playerLastPlay
PlayTime仓库issue:  https://github.com/A350xt/playtime/issues/1

**Comment by alex3236** [comment]
在 https://github.com/Aimerny/playerLastPlay/commit/2567d1c7aeecdc20353b9e865b205395dc17236a 前你的代码属于无许可代码，按惯例应当默认不允许他人以任何形式使用。但你现在创建了 LICENSE 且没有修改其他代码，因此可以视为你 repo 中所有代码从这刻起可以在遵循 GPL 3.0 的情况下使用。PlayTime 现在只需要同样添加 LICENSE 即可。

**Comment by Aimerny** [comment]
> 在 [Aimerny/playerLastPlay@2567d1c](https://github.com/Aimerny/playerLastPlay/commit/2567d1c7aeecdc20353b9e865b205395dc17236a) 前你的代码属于无许可代码，按惯例应当默认不允许他人以任何形式使用。但你现在创建了 LICENSE 且没有修改其他代码，因此可以视为你 repo 中所有代码从这刻起可以在遵循 GPL 3.0 的情况下使用。PlayTime 现在只需要同样添加 LICENSE 即可。

当然，如果添加了LICENSE我没意见。在5.11日0:00前如果作者未更新我会申请DMCA。

**Comment by AnzhiZhang** [comment]
## 事实

1. 根据代码对比结果，两个作品存在实质性相似
![image](https://github.com/MCDReforged/PluginCatalogue/assets/37402126/f139c6d6-6487-41c6-8222-0efefc6e08eb)
2. 原作品在收录 PlayTime 时属于保留所有权利状态，目前使用 GPL-3.0 协议释放了部分权利
3. 被指控侵权作品在收录时和现在的版权状态为保留所有权利

## 论证说理

1. 作为插件仓库，应当充分尊重知识产权与版权保护，尽到相关注意义务。PlayTime 侵犯了原作者的相关权利，收录该插件是一个错误，应当予以撤销
2. 根据中国（中华人民共和国知识产权法、中华人民共和国著作权法）、欧盟（伯尔尼公约）、美国（数字千年版权法案）等相关法律规定，插件仓库有移除该项目的道德和法律责任
4. 原作者已提供相关证据并提请移除以抑制传播，在确认事实和责任后，应当作出一定的行动

## 建议

1. 立即从插件仓库中移除 PlayTime 插件
2. 建议原作者使用 GitHub 投诉、法律诉讼等救济渠道维护自己的合法权益

**Comment by Aimerny** [comment]
看错了，那等处理完我再关闭
