### ISSUE TITLE
[Proposal] PR Check Action 功能更新：自动分类

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#358]
# PR 检查 action 的更新想法

可以对所有 PR 实现自动分类，分为插件添加/修改/删除，和插件库本身的修改

该功能的灵感来自于 CFPAOrg 的 PR 检查机器人，例：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/4490

<details>
<summary>截图</summary>
<img src="https://github.com/MCDReforged/PluginCatalogue/assets/37402126/92791fbc-dd52-4ae1-8399-6dcab41cb672"/>
</details>

### 插件库自身修改

自动添加 tag，例如 `PluginCatalogue change`

### 插件修改

1. 自动添加 tag，例如 `plugins update`
2. 自动发布一条消息，包括：
    1. 列出修改的插件列表，使用超链接帮助定位
    2. 列出涉及的插件的基本信息
    3. 运行一些基础检查，例如路径、meta、作者是否为仓库所有者等

## 优点

1. 列出有用的基本信息，帮助判断
2. 避免检查遗漏，例如增加插件路径不对等情况，这在以前已经发生过，审核人员未发现路径不对
3. 将检查未通过的项目通过消息提醒，不需要手动查找 action 定位问题，过去的方法需要更多经验和时间

**Comment by alex3236** [comment]
现在似乎 gh-action 权限不够没法回复消息。倒是放action summary里面

**Comment by AnzhiZhang** [comment]
> 现在似乎 gh-action 权限不够没法回复消息。倒是可以放action summary里面

https://github.com/actions/github-script?tab=readme-ov-file#comment-on-an-issue

**Comment by alex3236** [comment]
> https://github.com/actions/github-script?tab=readme-ov-file#comment-on-an-issue

我的意思是 Fallen 没给权限
