### ISSUE TITLE
关于添加插件，一个不成熟的想法

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#389]
制作一个 PR Bot，作为 GitHub App。作者只需在自己的仓库操作，bot 自动创建 PR。甚至可以做到发版同步，解决保存不同版本 meta 的问题。例：https://github.com/JuliaRegistries/Registrator.jl?tab=readme-ov-file#via-the-github-app

_Originally posted by @AnzhiZhang in https://github.com/MCDReforged/PluginCatalogue/issues/386#issuecomment-2316622918_

**Comment by alex3236** [comment]
真要考虑执行的话，工程量相当大，改动也相当多，还要一并改动 website

**Comment by AnzhiZhang** [comment]
website 不需要变动，依然可以维持目前的 meta 标准，毕竟是不成熟的方案，牵扯一定是会不少的，还没有收集和论证
