### ISSUE TITLE
feature: 自动标记/关闭不活跃的 Issue/PR

### ISSUE THREAD

**Issue by alex3236** [MCDReforged/PluginCatalogue#393]
See: https://github.com/MCDReforged/PluginCatalogue/pull/392
Also: _(https://github.com/MCDReforged/PluginCatalogue/pull/392#issuecomment-2334205742 by @AnzhiZhang )_

- 标签 inactive 会不会比 stale 更好？
- 豁免标签，有些长期未实现的 feature issue 是否值得被标记为 stale？
- 考虑豁免已分配的 issue
- 如果 PR 在等待更高权限的管理员 review，如何豁免，还是按计划关闭？

**Comment by alex3236** [comment]
> 标签 inactive 会不会比 stale 更好？

这个action叫stale，stale是默认值，可以讨论

> 豁免标签，有些长期未实现的 feature issue 是否值得被标记为 stale？

可以豁免标签，至于长期未实现依旧可以视为不活跃（和上面一点可以一起讨论）

> 考虑豁免已分配的 issue

这个倒是可以

> 如果 PR 在等待更高权限的管理员 review，如何豁免，还是按计划关闭？

在标记时提醒发布者，如果是review没有完成，就ping一下reviewer

https://github.com/MCDReforged/PluginCatalogue/blob/8d18fb7fcb5ff4da412b41ab7d5e17830d840109/.github/workflows/stale.yml#L15

**Comment by AnzhiZhang** [comment]
然后就会没有更多的人来讨论了，然后这个被标记为 stale（
