### ISSUE TITLE
PR 自动检查单强制更新

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#400]
是否有命令或复选框，可以输入命令，或修改报告中的复选框，强制刷新检查的报告？

**Comment by alex3236** [comment]
用复选框的话 workflow 触发次数会有点多，我的想法是在加上 refresh label 的时候强制刷新

**Comment by AnzhiZhang** [comment]
更新一下消息，添加相关的提示？

**Comment by alex3236** [comment]
> 更新一下消息，添加相关的提示？

https://github.com/MCDReforged/PluginCatalogue/blob/5e76755f7283c7cdc6605617023fd994154b150e/.github/workflows/scripts/utilities.py#L252
