### ISSUE TITLE
README的内部跳转不生效

### ISSUE THREAD

**Issue by XueK66** [MCDReforged/PluginCatalogue#401]
markdown语法中支持内部标题之内的跳转
但[MCDR仓库界面](https://mcdreforged.com/en/plugin/)的插件readme无法跳转

例子如下：
# 目录
- [目录](#目录)
- [config](#config)

# config
xxx

发现者: @Seungmin922

**Comment by alex3236** [comment]
是在 https://mcdreforged.com/en/plugin/ 里面无法跳转吧？

**Comment by XueK66** [comment]
是嘟

**Comment by alex3236** [comment]
> 是嘟

去 https://github.com/MCDReforged/website/issues 反馈哦

**Comment by alex3236** [comment]
fyi:
在 website 实现相关功能之前，如有相关需要可访问 [Github 中的插件仓库](https://github.com/MCDReforged/PluginCatalogue/blob/catalogue/readme-zh_cn.md)
但里面只有 introduction 没有 readme（
