### ISSUE TITLE
是否可以在一个PR中同时提交同一插件的多个子插件

### ISSUE THREAD

**Issue by Mooling0602** [MCDReforged/PluginCatalogue#404]
详细解释：
本人开发了基于[Matrix](https://matrix.org)的消息互通插件[MatrixSync](https://mcdreforged.com/zh-CN/plugin/matrix_sync)，且基于该插件同时开发了多个不同功能的子包（即依赖该插件的子插件）
如果按贡献指南中的“添加插件时，请将多个插件分开 PR”，那么将不得不为子包提交多个PR，但由于子包的目的都是扩展主插件功能，提交多个PR会比较繁琐，若能够集中在一起集中审核将提高处理效率
因此我想将这些子包合并在一起，并创建一个msync_packs分支，然后使用该分支提交PR入库，后续有变动也仍然通过该分支处理，不知是否可行（其他与MatrixSync无关的插件仍然分开提交）
为什么要提交入库这些子插件：
方便用户通过插件管理器直接安装
为什么不把子包都合并在一个插件内发布：
可能含有用户不需要的功能，分开供用户自行选择是更好的方案

**Comment by alex3236** [comment]
不建议把所有子包上传到插件库。作为参考，您可以：
- 考虑实现自己的插件系统，例如 [CBR](https://github.com/R1ckyH/ChatBridgeReforged)
- 所有子包合并为一个，通过配置文件控制特性开关

**Comment by AnzhiZhang** [comment]
MCDR 插件系统没有子插件的概念，如果需要类似 CBR 一样的多个功能模块，可以制作类似的实现，或发布为多个插件添加到插件库中。根据贡献指南，请为每一个插件创建一个 PR。至于插件之间的依赖关系，正确声明即可，请考虑到插件管理器的自动安装功能
