### ISSUE TITLE
description 没有提供多语言的，检查报告不标记语言

### ISSUE THREAD

**Issue by AnzhiZhang** [MCDReforged/PluginCatalogue#409]
插件 Signal Container 仅提供了[单语言 description](https://github.com/Lazy-Bing-Server/SignalContainer-MCDR/blob/master/mcdreforged.plugin.json)，但[检查报告](https://github.com/MCDReforged/PluginCatalogue/pull/408#issuecomment-2367678627)显示插件仅提供了英文描述，建议改为不标记语言。

**Comment by alex3236** [comment]
`description` 从 Metadata 到 MetaInfo 的过程中丢失了一些内容
要处理的话，以下两种都会是不标记状态
```json
"description": "desc"

"description": {
    "en_us": "desc"
}
```

**Comment by AnzhiZhang** [comment]
1. 更新 MetaInfo 的标准
2. 关闭此问题

**Comment by AnzhiZhang** [comment]
en_us 在 MetaInfo 中为默认语言且总是存在
