### ISSUE TITLE
一个可以一键安装想要的MCDR插件应用

### ISSUE THREAD

**Issue by cyf-gh** [MCDReforged/PluginCatalogue#70]
GUI web界面，逻辑清晰，脚本一键安装。

教程视频：http://www.bilibili.com/video/BV18a4y1E7T5
应用站点：https://www.cyf-cloud.cn/#/util/mcdrPlg

如果觉得可以的话麻烦收录一下。

**Comment by GamerNoTitle** [comment]
稍微瞄了一眼 你这个clone的时候把我那个Waypoints的中英文版都clone了（笑哭）

对于有中英文的插件，你可以试着把它分开，要不然两份插件有可能会导致一些问题

就拿Waypoints做例子，如果你有两份，那输入相关指令的时候就有两个线程进行反馈，然后会得到两份结果，而且加入路径点的时候会加入两份（总之就是导致不可预料的后果）

不过你这个不算是MCDR插件，所以说决定权并不在我手上，我只能给你提意见

**Comment by zhang-anzhi** [comment]
看了一下，感觉很不错啊
界面能再优化一下人性化一点就更好了
不过这个添加到MCDR仓库就要看佛冷的意思了
我觉得加到[插件市场](https://github.com/MCDReforged-Plugins/PluginCatalogue)可能更合适，不过这样的一个插件选购应用添加到插件市场也要佛冷决定的
另外想问一下这个的实现原理，如何获取的插件列表，如何保证及时更新

**Comment by GamerNoTitle** [comment]
> 看了一下，感觉很不错啊
> 界面能再优化一下人性化一点就更好了
> 不过这个添加到MCDR仓库就要看佛冷的意思了
> 我觉得加到[插件市场](https://github.com/MCDReforged-Plugins/PluginCatalogue)可能更合适，不过这样的一个插件选购应用添加到插件市场也要佛冷决定的
> 另外想问一下这个的实现原理，如何获取的插件列表，如何保证及时更新

+1

**Comment by zhang-anzhi** [comment]
我这边试用了一下也发现一个问题
![image](https://user-images.githubusercontent.com/37402126/91676976-04f32a00-eb74-11ea-9b3b-f0996844026c.png)
你的实现原理是将选择的插件的整个仓库clone下来，然后将py文件复制进去
就会导致一个插件库里有中英文插件的同时安装，如 `QuickBackM`, `Waypoints`
还有我这种一堆插件放[一个仓库](https://github.com/zhang-anzhi/MCDReforgedPlugins)的，选择一个就会clone整个仓库下来，10多个插件一起下载，这是插件大礼包嘛（我没给钱）
```batch
### clone所有插件 ###
if [ ! -d ./.plg ]; then
    mkdir ./plg
fi
cd ./plg
git clone https://github.com/zhang-anzhi/MCDReforgedPlugins.git
git clone https://github.com/zhang-anzhi/MCDReforgedPlugins.git
```

**Comment by cyf-gh** [comment]
> 我这边试用了一下也发现一个问题
> ![image](https://user-images.githubusercontent.com/37402126/91676976-04f32a00-eb74-11ea-9b3b-f0996844026c.png)
> 你的实现原理是将选择的插件的整个仓库clone下来，然后将py文件复制进去
> 就会导致一个插件库里有中英文插件的同时安装，如 `QuickBackM`, `Waypoints`
> 还有我这种一堆插件放[一个仓库](https://github.com/zhang-anzhi/MCDReforgedPlugins)的，选择一个就会clone整个仓库下来，10多个插件一起下载，这是插件大礼包嘛（我没给钱）
> 
> ```batchfile
> ### clone所有插件 ###
> if [ ! -d ./.plg ]; then
>     mkdir ./plg
> fi
> cd ./plg
> git clone https://github.com/zhang-anzhi/MCDReforgedPlugins.git
> git clone https://github.com/zhang-anzhi/MCDReforgedPlugins.git
> ```

插件仓库格式不统一确实是个大问题，暂时考虑到的解决方案是可以在复制py文件的时候，如果py文件大于1个则逐个询问用户是否需要该插件。
另外有些插件还需要前置插件，而现在的一键安装并不会嗅探到前置插件。我觉得要解决这些问题的话需要大家制定一个标准的mcdr插件仓库结构。

**Comment by cyf-gh** [comment]
> 看了一下，感觉很不错啊
> 界面能再优化一下人性化一点就更好了
> 这样的一个插件选购应用添加到插件市场需要佛冷来决定，决定权就不在我们手上了
> 另外想问一下这个的实现原理，如何获取的插件列表，如何保证及时更新
> 
> 改了一下，我看错了以为是MCDR的issue。。。
https://github.com/MCDReforged-Plugins/PluginCatalogue/issues/70#issuecomment-683519200


> 看了一下，感觉很不错啊
> 界面能再优化一下人性化一点就更好了
> 这样的一个插件选购应用添加到插件市场需要佛冷来决定，决定权就不在我们手上了
> 另外想问一下这个的实现原理，如何获取的插件列表，如何保证及时更新
> 
> 改了一下，我看错了以为是MCDR的issue。。。

https://github.com/cyf-gh/MCDRPluginCataJson
我手动创建并提取的json文件，结构是我自己定义的。页面会读取这个文件并解析成ui形式。
如果网页有什么bug或者修改意见也可以在这里issue。

**Comment by cyf-gh** [comment]
> 稍微瞄了一眼 你这个clone的时候把我那个Waypoints的中英文版都clone了（笑哭）
> 
> 对于有中英文的插件，你可以试着把它分开，要不然两份插件有可能会导致一些问题
> 
> 就拿Waypoints做例子，如果你有两份，那输入相关指令的时候就有两个线程进行反馈，然后会得到两份结果，而且加入路径点的时候会加入两份（总之就是导致不可预料的后果）
> 
> 不过你这个不算是MCDR插件，所以说决定权并不在我手上，我只能给你提意见

https://github.com/MCDReforged-Plugins/PluginCatalogue/issues/70#issuecomment-683519200

**Comment by zhang-anzhi** [comment]
> 另外有些插件还需要前置插件，而现在的一键安装并不会嗅探到前置插件。我觉得要解决这些问题的话需要大家制定一个标准的mcdr插件仓库结构。

前置插件的问题最好的办法还是看官方解决，佛冷可能会推第一个版本号做插件注册
而仓库不统一这个问题肯定是无法统一的，每个人有自己的开源风格，不过有一个特点就是在插件仓库提供的地址直接打开一定是仓库根目录或者仓库里放这个插件的目录，这个目录里面会有readme文件和插件.py文件，只需要识别这个目录下的文件列表即可，有多个.py文件可以询问用户

总之想要良好的运行这样的安装工具最好的办法就是**注册**，但是插件注册到你这里是不可能的，只能自己解析啦（再次强调唯一相同点就是提供的插件链接目录下一定有插件文件，但是需要下载的可能不止这个插件或者有多个版本）

**Comment by cyf-gh** [comment]
> > 另外有些插件还需要前置插件，而现在的一键安装并不会嗅探到前置插件。我觉得要解决这些问题的话需要大家制定一个标准的mcdr插件仓库结构。
> 
> 前置插件的问题最好的办法还是看官方解决，佛冷可能会推第一个版本号做插件注册
> 而仓库不统一这个问题肯定是无法统一的，每个人有自己的开源风格，不过有一个特点就是在插件仓库提供的地址直接打开一定是仓库根目录或者仓库里放这个插件的目录，这个目录里面会有readme文件和插件.py文件，只需要识别这个目录下的文件列表即可，有多个.py文件可以询问用户
> 
> 总之想要良好的运行这样的安装工具最好的办法就是**注册**，但是插件注册到你这里是不可能的，只能自己解析啦（再次强调唯一相同点就是提供的插件链接目录下一定有插件文件，但是需要下载的可能不止这个插件或者有多个版本）

我也只是写了个辅助工具，如果官方有支持对前置插件做出规范改动的话我也会及时更上。
顺便我不知道佛冷是谁...你们有讨论群之类的吗？我希望能更方便的交流并获得改进意见。

**Comment by GamerNoTitle** [comment]
佛冷是[@Fallen_Breath](https://github.com/Fallen-Breath)，MCDR就是他做的
讨论群在[https://github.com/Fallen-Breath/MCDReforged/blob/master/doc/readme_cn.md](https://github.com/Fallen-Breath/MCDReforged/blob/master/doc/readme_cn.md)里面有

> > > 另外有些插件还需要前置插件，而现在的一键安装并不会嗅探到前置插件。我觉得要解决这些问题的话需要大家制定一个标准的mcdr插件仓库结构。
> > 
> > 
> > 前置插件的问题最好的办法还是看官方解决，佛冷可能会推第一个版本号做插件注册
> > 而仓库不统一这个问题肯定是无法统一的，每个人有自己的开源风格，不过有一个特点就是在插件仓库提供的地址直接打开一定是仓库根目录或者仓库里放这个插件的目录，这个目录里面会有readme文件和插件.py文件，只需要识别这个目录下的文件列表即可，有多个.py文件可以询问用户
> > 总之想要良好的运行这样的安装工具最好的办法就是**注册**，但是插件注册到你这里是不可能的，只能自己解析啦（再次强调唯一相同点就是提供的插件链接目录下一定有插件文件，但是需要下载的可能不止这个插件或者有多个版本）
> 
> 我也只是写了个辅助工具，如果官方有支持对前置插件做出规范改动的话我也会及时更上。
> 顺便我不知道佛冷是谁...你们有讨论群之类的吗？我希望能更方便的交流并获得改进意见。

**Comment by eagle3236** [comment]
目前的最优解应该是类似于 #89 
作者一次性添加后可永不维护，无需第三方服务器，可无人值守。
