### ISSUE TITLE
添加 “是否支持 MCDR 1.x” 表头

### ISSUE THREAD

**Issue by eagle3236** [MCDReforged/PluginCatalogue#93]
现在有一大摞插件不支持 MCDR 1.x 以及一大堆只支持MCDR 1.x
设想如下：
| 类型 | 兼容性 | 意义 |
| - | - | - |
| 双向支持 | **A** | All |
| 只支持 MCDR 1.x | **O** | Only 1.x |
| 只支持 MCDR 0.x | - | No |

兼容性应位于插件名表头之前。
例：
| 1.x | Name | Maintainer | Function
| - | - | - | - |
| O | daycount-NBT | Alex3236 | An easy-use daycount |
| - | seed | ChunkAsgore | A plugin for querying server map seeds for MCDReforged. |
| A | Here | Fallen_Breath | Broadcast your position and high light yourself

**Comment by zhang-anzhi** [comment]
建议既然标记兼容性就直接一步到位改进成机器可读插件库

**Comment by eagle3236** [comment]
> 建议既然标记兼容性就直接一步到位改进成机器可读插件库

所以你弄了吗？要读markdown还是重建？

**Comment by zhang-anzhi** [comment]
> > 建议既然标记兼容性就直接一步到位改进成机器可读插件库
> 
> 所以你弄了吗？要读markdown还是重建？

#89
