### ISSUE TITLE
插件管理器实现思路

### ISSUE THREAD

**Issue by rickyhoho** [MCDReforged/PluginCatalogue#94]
续 #89 
# 就目前讨论的方案记录
---
目前的打算是让作者在插件仓库注册一个`LTS`版本的`plugin_info,json(或yml)`
然后插件管理器透过读取`plugin_info.json`获取插件的大约资讯和连接
以供给用户暂时性观看。

如果需要详细资讯在透过`plugin_info.json`内的连接前往作者的仓库
再在作者的仓库里面读取作者自己维护的`data.json(或yml)`
然后从`data.json`里面的文件决定具体操作流程

---
# 插件仓库内的文件结构大概如下
![image](https://user-images.githubusercontent.com/24563814/108497727-de25dd00-72e6-11eb-9810-eac5a1a9058b.png)

- `/plugin_info.json(有可能变成yml)`
```
id: [str]
author: list[str] or [str]
link: [str]
name: [str]
info: {
    en_us: desc[str]
    zh_cn: desc[str]
}
---
```
# 作者仓库的文件结构
作者仓库目前还没有大约的共识，故指留下大约的文件结构，内容暂时没有。

- `my_plugin.py`: 插件/插件入口 
- `readme.md`: 自述文件
- `plugin/mcdreforged.plugin .yml/.json`: 名称未定，作者需要维护的插件信息
- `my_plugin/`: 非必选，插件所需其他文件
- ...

**Comment by zhang-anzhi** [comment]
插件管理器自动安装python依赖，需要可配置venv路径

**Comment by zhang-anzhi** [comment]
将这个思路进行了整理和细化，#100

**Comment by Fallen-Breath** [comment]
已于 MCDR 2.0 实现插件库规范

文档：https://mcdreforged.readthedocs.io/zh_CN/latest/plugin_dev/plugin_catalogue.html
